language: ruby

rvm:
  - 2.1.5

env:
  global:
    secure: M4SUPhx20BmBiX3defVjog5/OmX9NTuekcuRDIsgC1ml0FD2RO1WCoqhFYSVeltwQ2fekKZkW/jTcuVA5Sq7pTIC3D6YwTfThOTWns4nWee9q//Imr+VUVDmhwAAYJ8H1+r/AOwzpp9vsLWgd7rW1UJxlkfeTkA2Tse0DFOHqs8=

notifications:
  email:
    recipients:
      - jasnow@hotmail.com
    on_success: change
    on_failure: always
