language: ruby

rvm:
  - 2.1.0

secure: "egxZBZqXhgKpV0rxXSinymvxQc70Y41Z7N5QvouMLXc8o2ydC7alV7k8OvdF6gwY+rOQqOtGYDW3nwem/wSSa3hU5Vv5+5Z2jDKZ0R40Ojkbj7Ma/jTIfYBGRhu+jkPBNIb5gOHddTbavkyASxSFNpDoTyOir90Z+EWR0Tm8pI8="

notifications:
  email:
    recipients:
      - jasnow@hotmail.com
    on_success: change
    on_failure: always
